// Bounded reader for multipart snapshots generated by Chrome. No HTML executes.
const decoder = new TextDecoder("windows-1252");

function headers(text) {
  const result = new Map();
  for (const line of text.replace(/\r?\n[\t ]+/g, " ").split(/\r?\n/)) {
    const colon = line.indexOf(":");
    if (colon > 0) result.set(line.slice(0, colon).trim().toLowerCase(), line.slice(colon + 1).trim());
  }
  return result;
}

function headerEnd(text, offset = 0) {
  const crlf = text.indexOf("\r\n\r\n", offset);
  const lf = text.indexOf("\n\n", offset);
  if (crlf !== -1 && (lf === -1 || crlf < lf)) return {index: crlf, body: crlf + 4};
  if (lf !== -1) return {index: lf, body: lf + 2};
  throw new Error("快照中缺少 MIME 头分隔符");
}

function decodeBody(body, encoding) {
  if (encoding === "base64") {
    const binary = atob(decoder.decode(body).replace(/\s/g, ""));
    return Uint8Array.from(binary, (char) => char.charCodeAt(0));
  }
  if (encoding === "quoted-printable") {
    const bytes = [];
    for (let i = 0; i < body.length; i++) {
      if (body[i] !== 61) {bytes.push(body[i]); continue;}
      if (body[i + 1] === 10) {i++; continue;}
      if (body[i + 1] === 13 && body[i + 2] === 10) {i += 2; continue;}
      const hex = String.fromCharCode(body[i + 1] || 0, body[i + 2] || 0);
      if (!/^[0-9a-f]{2}$/i.test(hex)) throw new Error("快照包含无效的 quoted-printable 编码");
      bytes.push(parseInt(hex, 16));
      i += 2;
    }
    return Uint8Array.from(bytes);
  }
  if (["", "7bit", "8bit", "binary"].includes(encoding)) return body.slice();
  throw new Error(`快照使用了暂不支持的编码：${encoding}`);
}

export function extractImages(input) {
  const bytes = input instanceof Uint8Array ? input : new Uint8Array(input);
  // This decoder maps each byte to one UTF-16 code unit. Indexes therefore
  // remain byte indexes; bodies are sliced from the original byte array.
  const text = decoder.decode(bytes);
  const rootEnd = headerEnd(text);
  const root = headers(text.slice(0, rootEnd.index));
  const contentType = root.get("content-type") || "";
  if (!/^multipart\/related\b/i.test(contentType)) throw new Error("需要 Chrome 生成的 multipart/related 快照");
  const boundaryMatch = contentType.match(/\bboundary\s*=\s*(?:"([^"]+)"|([^;\s]+))/i);
  if (!boundaryMatch) throw new Error("快照缺少 MIME 边界");
  const boundary = boundaryMatch[1] || boundaryMatch[2];
  const escaped = boundary.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const delimiters = [...text.matchAll(new RegExp(`(?:^|\\r?\\n)--${escaped}(--)?[\\t ]*(?:\\r?\\n|$)`, "g"))];
  if (delimiters.length < 2 || !delimiters.at(-1)[1]) throw new Error("快照没有完整的结束边界");
  const result = [];
  for (let i = 0; i < delimiters.length - 1; i++) {
    const delimiter = delimiters[i];
    if (delimiter[1]) break;
    const start = delimiter.index + delimiter[0].length;
    const end = delimiters[i + 1].index;
    const split = headerEnd(text, start);
    if (split.body > end) throw new Error("快照资源头越过了 MIME 边界");
    const part = headers(text.slice(start, split.index));
    const mime = (part.get("content-type") || "").split(";")[0].trim().toLowerCase();
    if (!mime.startsWith("image/")) continue;
    const location = part.get("content-location");
    if (!location) throw new Error("图片资源缺少 Content-Location");
    const encoding = (part.get("content-transfer-encoding") || "").toLowerCase();
    const data = decodeBody(bytes.subarray(split.body, end), encoding);
    if (!data.length) throw new Error("快照中的图片文件为空");
    result.push({location, mime, bytes: data});
  }
  return result;
}

export function matchResource(image, resources) {
  // Chrome may label cached srcset bytes using src rather than currentSrc.
  for (const alias of new Set([image.currentSrc, image.src].filter(Boolean))) {
    const matches = resources.filter((resource) => resource.location === alias);
    if (matches.length > 1) throw new Error("同一地址对应多个快照资源，需要单独处理");
    if (matches.length === 1) return matches[0];
  }
  return null;
}

export function safeName(value, fallback = "未命名页面") {
  let result = String(value).normalize("NFC").replace(/[<>:"/\\|?*\u0000-\u001f]/g, "_").replace(/[. ]+$/g, "").trim();
  if (!result || /^\.{1,2}$/.test(result)) result = fallback;
  if (/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(result)) result = `_${result}`;
  return [...result].slice(0, 100).join("").replace(/[. ]+$/g, "") || fallback;
}

export function extensionFor(mime) {
  const extensions = {"image/jpeg": "jpg", "image/jpg": "jpg", "image/pjpeg": "jpg", "image/png": "png", "image/apng": "png", "image/gif": "gif", "image/webp": "webp", "image/avif": "avif", "image/svg+xml": "svg", "image/bmp": "bmp", "image/x-icon": "ico", "image/vnd.microsoft.icon": "ico"};
  const extension = extensions[mime];
  if (!extension) throw new Error(`暂不支持保存此图片格式：${mime}`);
  return extension;
}
